java:
  runtime:
    version: 17

spring:
  datasource:
    url: jdbc:postgres://dpg-d0u6lsm3jp1c73fhb9kg-a:5432/videomentor_kubw
    username: videomentor
    password: QXnt5O0DBDromHTveKHzjO2PlEHpYGvi
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration: 36000000

  url:
    host: https://api-video-finder.onrender.com
    path:
      playlist: playlists/
      video: videos/

  key: ${GOOGLE_API_KEY}
  cx: ${GOOGLE_CX}

playlist:
  id: PL3XiMCPOuJvnEpMJL2PpX7qo7JxXt9f32
