spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/videomentor
    # url: jdbc:postgresql:///videomentor?cloudSqlInstance=videomentor-378613:us-central1:db-videomentor&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=Xava0199
    username: postgres
    password: Xava0199
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        formate_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

server:
  error:
    include-stacktrace: never
