java:
  runtime:
    version: 17
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
api:
  security:
    token:
      secret: '${JWT_SECRET:DAHFAKHFSBDJFHPQI3RIHF90284879GHFJFWKFNSDFJG3974}'
      expiration: 36000000
